# Source
https://www.youtube.com/playlist?list=PLOU2XLYxmsIIuiBfYad6rFYQU_jL2ryal

# 1. apple oragne Code (Google Developer)
https://www.youtube.com/watch?v=cKxRvEZd3Mw&list=PLT6elRN3Aer7ncFlaCz8Zz-4B5cnsrOMt


In [1]:
from sklearn import tree
features = [ [140,1],[130,1],[150,0],[170,0]]
labels = [0,0,1,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features,labels)
clf.predict([[145,1]])

array([0])

 # 2. iris data (Google Developer)
 https://www.youtube.com/watch?v=tNa99PG8hR8&list=PLT6elRN3Aer7ncFlaCz8Zz-4B5cnsrOMt&index=2&spfreload=10

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
print (iris.feature_names)
print (iris.target_names)
print (iris.data[0])
print (iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
0


In [3]:
test_idx = [0,50,100]

In [5]:
import numpy as np
#training data
train_target = np.delete(iris.target,test_idx,axis=0)
train_data = np.delete(iris.data, test_idx,axis = 0)

In [6]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [7]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [8]:
print(test_target)
print(clf.predict(test_data))

[0 1 2]
[0 1 2]


########################################################
########################################################

More advance way to split train test and find accuracy

In [9]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [11]:
# create training ang testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=55)
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [12]:
# tree as classifier
from sklearn import tree
clf = tree.DecisionTreeClassifier()

clf.fit(X_train,y_train)
prediction = clf.predict(X_test)
# find accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)


0.96666666666666667

In [13]:
# KNN as classifier
from sklearn import neighbors 
clf = neighbors.KNeighborsClassifier()

clf.fit(X_train,y_train)
prediction = clf.predict(X_test)
# find accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)

0.96666666666666667

########################################################
########################################################

# 3. Build Own Classifier (Google Developer)
https://www.youtube.com/watch?v=AoeEHqVSNOw&list=PLT6elRN3Aer7ncFlaCz8Zz-4B5cnsrOMt&index=6

In [14]:
import random
class ScrappyKNN():
    def fit(self,X_train,y_train):
        self.X_train = X_train
        self.y_train = y_train
    def predict(self,X_test):
        prediction = []
        for row in X_test:
            label = random.choice(self.y_train)
            prediction.append(label)
        return prediction

In [15]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=55)
clf = ScrappyKNN()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.36666666666666664

In [16]:
# lets write a code for 1-KNN

In [17]:
from scipy.spatial import distance
def euc(a,b):
    return distance.euclidean(a,b)

class ScrappyKNN():
    def fit(self,X_train,y_train):
        self.X_train = X_train
        self.y_train = y_train
        
    def predict(self,X_test):
        prediction = []
        for row in X_test:
            label = self.closest(row)
            prediction.append(label)
        return prediction
    
    def closest(self,row):
        best_dist = euc (row,self.X_train[0])
        best_index = 0
        for i in range(1,len(self.X_train)):
            dist = euc(row,self.X_train[i])
            if dist < best_dist:
                best_dist = dist
                best_index = i
        return self.y_train[best_index]

In [18]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=55)
clf = ScrappyKNN()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.96666666666666667